language: python
python:
  - "2.6"
  - "2.7"
install: pip install -r requirements.txt --use-mirrors
before_script: sudo ./.travis-pre-run.py /usr/local
script: ./.travis-runner.py -l /usr/local/google_appengine ./tests
notifications:
  email:
    - d-eve-lopment@googlegroups.com
